// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizDemo.Datas;

namespace QuizDemo.Migrations
{
    [DbContext(typeof(ApplicationSqlContext))]
    [Migration("20220324190809_Add-Seed-Data")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Thai_100_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuizDemo.Datas.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HN")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "test01@quiz.com",
                            FirstName = "ทดสอบ01",
                            HN = "000001",
                            LastName = "นามสกุล01",
                            Phone = "0810000001"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "test02@quiz.com",
                            FirstName = "ทดสอบ02",
                            HN = "000002",
                            LastName = "นามสกุล02",
                            Phone = "0810000002"
                        },
                        new
                        {
                            Id = 3L,
                            Email = "test03@quiz.com",
                            FirstName = "ทดสอบ03",
                            HN = "000003",
                            LastName = "นามสกุล03",
                            Phone = "0810000003"
                        },
                        new
                        {
                            Id = 4L,
                            Email = "test04@quiz.com",
                            FirstName = "ทดสอบ04",
                            HN = "000004",
                            LastName = "นามสกุล04",
                            Phone = "0810000004"
                        },
                        new
                        {
                            Id = 5L,
                            Email = "test05@quiz.com",
                            FirstName = "ทดสอบ05",
                            HN = "000005",
                            LastName = "นามสกุล05",
                            Phone = "0810000005"
                        },
                        new
                        {
                            Id = 6L,
                            Email = "test06@quiz.com",
                            FirstName = "ทดสอบ06",
                            HN = "000006",
                            LastName = "นามสกุล06",
                            Phone = "0810000006"
                        },
                        new
                        {
                            Id = 7L,
                            Email = "test07@quiz.com",
                            FirstName = "ทดสอบ07",
                            HN = "000007",
                            LastName = "นามสกุล07",
                            Phone = "0810000007"
                        },
                        new
                        {
                            Id = 8L,
                            Email = "test08@quiz.com",
                            FirstName = "ทดสอบ08",
                            HN = "000008",
                            LastName = "นามสกุล08",
                            Phone = "0810000008"
                        },
                        new
                        {
                            Id = 9L,
                            Email = "test09@quiz.com",
                            FirstName = "ทดสอบ09",
                            HN = "000009",
                            LastName = "นามสกุล09",
                            Phone = "0810000009"
                        },
                        new
                        {
                            Id = 10L,
                            Email = "test10@quiz.com",
                            FirstName = "ทดสอบ10",
                            HN = "000010",
                            LastName = "นามสกุล10",
                            Phone = "0810000010"
                        },
                        new
                        {
                            Id = 11L,
                            Email = "test11@quiz.com",
                            FirstName = "ทดสอบ11",
                            HN = "000011",
                            LastName = "นามสกุล11",
                            Phone = "0810000011"
                        },
                        new
                        {
                            Id = 12L,
                            Email = "test12@quiz.com",
                            FirstName = "ทดสอบ12",
                            HN = "000012",
                            LastName = "นามสกุล12",
                            Phone = "0810000012"
                        },
                        new
                        {
                            Id = 13L,
                            Email = "test13@quiz.com",
                            FirstName = "ทดสอบ13",
                            HN = "000013",
                            LastName = "นามสกุล13",
                            Phone = "0810000013"
                        },
                        new
                        {
                            Id = 14L,
                            Email = "test14@quiz.com",
                            FirstName = "ทดสอบ14",
                            HN = "000014",
                            LastName = "นามสกุล14",
                            Phone = "0810000014"
                        },
                        new
                        {
                            Id = 15L,
                            Email = "test15@quiz.com",
                            FirstName = "ทดสอบ15",
                            HN = "000015",
                            LastName = "นามสกุล15",
                            Phone = "0810000015"
                        },
                        new
                        {
                            Id = 16L,
                            Email = "test16@quiz.com",
                            FirstName = "ทดสอบ16",
                            HN = "000016",
                            LastName = "นามสกุล16",
                            Phone = "0810000016"
                        },
                        new
                        {
                            Id = 17L,
                            Email = "test17@quiz.com",
                            FirstName = "ทดสอบ17",
                            HN = "000017",
                            LastName = "นามสกุล17",
                            Phone = "0810000017"
                        },
                        new
                        {
                            Id = 18L,
                            Email = "test18@quiz.com",
                            FirstName = "ทดสอบ18",
                            HN = "000018",
                            LastName = "นามสกุล18",
                            Phone = "0810000018"
                        },
                        new
                        {
                            Id = 19L,
                            Email = "test19@quiz.com",
                            FirstName = "ทดสอบ19",
                            HN = "000019",
                            LastName = "นามสกุล19",
                            Phone = "0810000019"
                        },
                        new
                        {
                            Id = 20L,
                            Email = "test20@quiz.com",
                            FirstName = "ทดสอบ20",
                            HN = "000020",
                            LastName = "นามสกุล20",
                            Phone = "0810000020"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
