// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizDemo.Datas;

namespace QuizDemo.Migrations
{
    [DbContext(typeof(ApplicationSqlContext))]
    [Migration("20220323194810_Add-Attribute-Required")]
    partial class AddAttributeRequired
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Thai_100_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuizDemo.Datas.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HN")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "test01@quiz.com",
                            FirstName = "ทดสอบ01",
                            HN = "000001",
                            LastName = "นามสกุล01",
                            Phone = "0810000001"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "test02@quiz.com",
                            FirstName = "ทดสอบ02",
                            HN = "000002",
                            LastName = "นามสกุล02",
                            Phone = "0810000002"
                        },
                        new
                        {
                            Id = 3L,
                            Email = "test03@quiz.com",
                            FirstName = "ทดสอบ03",
                            HN = "000003",
                            LastName = "นามสกุล03",
                            Phone = "0810000003"
                        },
                        new
                        {
                            Id = 4L,
                            Email = "test04@quiz.com",
                            FirstName = "ทดสอบ04",
                            HN = "000004",
                            LastName = "นามสกุล04",
                            Phone = "0810000004"
                        },
                        new
                        {
                            Id = 5L,
                            Email = "test05@quiz.com",
                            FirstName = "ทดสอบ05",
                            HN = "000005",
                            LastName = "นามสกุล05",
                            Phone = "0810000005"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
